workflows:
  ios-release-build:
    name: iOS Release Build
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # Install CocoaPods and update repos
      - name: Install CocoaPods (if needed)
        script: |
          sudo gem install cocoapods
          pod repo update

      # Run flutter doctor to verify environment
      - name: Flutter Doctor
        script: |
          flutter doctor

      # Clean and fetch packages
      - name: Clean & Get Packages
        script: |
          flutter clean
          flutter pub get
          cd ios && pod install --repo-update
          cd ..

      # Precache iOS artifacts for flutter
      - name: Precache Flutter iOS artifacts
        script: |
          flutter precache --ios

      # Build iOS release without codesigning
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa
      - build/**/outputs/**/*.apk
