workflows:
  ios_release:
    name: ios release
    max_build_duration: 60
    environment:
      flutter: stable  # تأكد من استخدام النسخة المستقرة من Flutter
    scripts:
      # تنظيف المشروع وتحميل الحزم
      - flutter clean
      - flutter pub get
      - cd ios && pod install && cd ..
      # تحديث CocoaPods
      - pod install --project-directory=ios

      # بناء التطبيق على نظام iOS بدون توقيع الكود (no-codesign)
      - flutter build ios --release --no-codesign -v

    # يمكنك إضافة فحوصات أو إجراءات إضافية حسب الحاجة هنا
    artifacts:
      - build/ios/iphoneos/Runner.app # أو حسب المسار الخاص بتطبيقك


