workflows:
  ios_release:
    name: ios release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
