// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xp0uRzP7FnzlSnRrRXS-mMeyETnwA3g',
    appId: '1:656264487864:web:f4b40b2e9d27f799ede54d',
    messagingSenderId: '656264487864',
    projectId: 'smart-watch-7d76d',
    authDomain: 'smart-watch-7d76d.firebaseapp.com',
    storageBucket: 'smart-watch-7d76d.firebasestorage.app',
    measurementId: 'G-FNYQ4Q1VVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRDLiXgS66THbf1FLRyVEZgpVoVibXhw',
    appId: '1:656264487864:android:7d1a0f326da1f0a8ede54d',
    messagingSenderId: '656264487864',
    projectId: 'smart-watch-7d76d',
    storageBucket: 'smart-watch-7d76d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5WiyAOSpwVy7z3AtStc6H2DWn9awSns',
    appId: '1:656264487864:ios:68621684c21111a4ede54d',
    messagingSenderId: '656264487864',
    projectId: 'smart-watch-7d76d',
    storageBucket: 'smart-watch-7d76d.firebasestorage.app',
    iosBundleId: 'com.example.smartWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5WiyAOSpwVy7z3AtStc6H2DWn9awSns',
    appId: '1:656264487864:ios:68621684c21111a4ede54d',
    messagingSenderId: '656264487864',
    projectId: 'smart-watch-7d76d',
    storageBucket: 'smart-watch-7d76d.firebasestorage.app',
    iosBundleId: 'com.example.smartWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_xp0uRzP7FnzlSnRrRXS-mMeyETnwA3g',
    appId: '1:656264487864:web:82810266a0f5371bede54d',
    messagingSenderId: '656264487864',
    projectId: 'smart-watch-7d76d',
    authDomain: 'smart-watch-7d76d.firebaseapp.com',
    storageBucket: 'smart-watch-7d76d.firebasestorage.app',
    measurementId: 'G-1R9HPLYKNP',
  );
}
